services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: "admin"
      INIT_MEMORY: 4G
      MAX_MEMORY: 10G
      MOTD: "PUSSY + DIAMOND + WEED"
      ENABLE_ROLLING_LOGS: "true"
      VIEW_DISTANCE: 18
      USE_AIKAR_FLAGS: "true"
      TYPE: PURPUR
      # ENABLE_AUTOPAUSE: "true"
      # AUTOPAUSE_TIMEOUT_EST: 3600  # 1 hour
      # AUTOPAUSE_TIMEOUT_INIT: 600  # 10 minutes
      # AUTOPAUSE_TIMEOUT_KN: 120    # 2 minutes
      # AUTOPAUSE_PERIOD: 10         # 10 seconds
      # AUTOPAUSE_KNOCK_INTERFACE: eth0  # Set your network interface
      # ENABLE_AUTOSTOP: "TRUE"
      # AUTOSTOP_TIMEOUT_INIT: "1800"  # 30 minutes
      # AUTOSTOP_TIMEOUT_EST: "3600"   # 1 hour
      # AUTOSTOP_PERIOD: 10            # 10 seconds
      LOG_TIMESTAMP: TRUE
    restart: "no"
  rcon:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PORT: "25575"
      RWA_RCON_PASSWORD: "admin"
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
  backups:
    image: itzg/mc-backup
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: "admin"
      INITIAL_DELAY: "2m"
      BACKUP_METHOD: tar
      DEST_DIR: /backups
    volumes:
      - ./data:/data:ro  # Mounts the Minecraft server data directory read-only
      - ./backups:/backups  # Directory where backups will be stored
    restart: unless-stopped
volumes:
  rcon:
