services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: "admin"
      INIT_MEMORY: 4G
      MAX_MEMORY: 10G
      MOTD: "PUSSY + DIAMOND + WEED"
      ENABLE_ROLLING_LOGS: "true"
      OPS: "Chapoliiat"
      VIEW_DISTANCE: 18
      USE_AIKAR_FLAGS: "true"
      TYPE: PURPUR
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
    restart: unless-stopped
  rcon:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PORT: "25575"
      RWA_RCON_PASSWORD: "admin"
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
  backups:
    image: itzg/mc-backup
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: "admin"
      INITIAL_DELAY: "2m"
      BACKUP_METHOD: tar
      DEST_DIR: /backups
    volumes:
      - ./data:/data:ro  # Mounts the Minecraft server data directory read-only
      - ./backups:/backups  # Directory where backups will be stored
    restart: unless-stopped
volumes:
  rcon:
